<a href="https://colab.research.google.com/github/Niroshan2812/PlantDiseaseMLPrj/blob/main/PlantDisease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q kaggle


In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"niroshandh","key":"effcb12f74193ff5f69f6a68ec61fa4b"}'}

In [3]:
! mkdir ~/.kaggle


In [4]:
! cp kaggle.json ~/.kaggle/

In [5]:
! chomod 600 ~/.kaggle/kaggle.json


/bin/bash: line 1: chomod: command not found


In [6]:
!pip install opendatasets


In [7]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/vipoooool/new-plant-diseases-dataset")


Dataset URL: https://www.kaggle.com/datasets/vipoooool/new-plant-diseases-dataset


100%|██████████| 2.70G/2.70G [00:31<00:00, 93.3MB/s]


**Import Libraries**

In [8]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

Data preprocessing ~ training image

In [9]:

training_set =tf.keras.utils.image_dataset_from_directory(
    "/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,


)

Found 70295 files belonging to 38 classes.


Data preprocessing ~ validation image

In [10]:

training_set =tf.keras.utils.image_dataset_from_directory(
    "/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,


)

Found 17572 files belonging to 38 classes.


In [12]:
for x,y in training_set:
  print(x,x.shape)
  print(y,y.shape)
  break

tf.Tensor(
[[[[ 83.75  76.25  79.75]
   [168.   159.   164.  ]
   [170.   161.   166.  ]
   ...
   [172.   167.   174.  ]
   [175.   170.   177.  ]
   [171.   166.   173.  ]]

  [[ 90.5   81.5   86.5 ]
   [170.   161.   166.  ]
   [168.75 159.75 164.75]
   ...
   [173.5  168.5  175.5 ]
   [172.75 167.75 174.75]
   [171.25 166.25 173.25]]

  [[ 86.    78.    82.  ]
   [172.5  163.5  168.5 ]
   [173.5  164.5  169.5 ]
   ...
   [173.25 168.25 175.25]
   [169.25 164.25 171.25]
   [168.5  163.5  170.5 ]]

  ...

  [[ 83.5   75.75  77.5 ]
   [170.5  161.5  164.5 ]
   [161.75 152.75 155.75]
   ...
   [185.25 180.25 186.25]
   [182.75 177.75 183.75]
   [187.25 182.25 188.25]]

  [[ 85.25  77.25  79.25]
   [156.25 147.25 150.25]
   [177.   168.   171.  ]
   ...
   [185.25 180.25 186.25]
   [178.   173.   179.  ]
   [194.25 189.25 195.25]]

  [[ 86.75  78.75  80.75]
   [147.75 138.75 141.75]
   [188.5  179.5  182.5 ]
   ...
   [194.5  189.5  195.5 ]
   [176.75 171.75 177.75]
   [181.25 176.25 18

Building a model

In [1]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten
from tensorflow.keras.models import Sequential


In [2]:
model = Sequential()


Build Convolutioin layer

In [3]:
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=(128,128,3)))
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=(128,128,3)))
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

In [5]:
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=(128,128,3)))
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

In [6]:
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=(128,128,3)))
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

In [7]:
model.add(Flatten())

In [8]:
model.add(Dense(units=1024, activation="relu"))


In [9]:
model.add(Dense(units=38, activation="softmax"))


Comppiling model

In [10]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 64, 64, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 64, 64, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 32, 32, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 32, 32, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 32, 32, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 16, 16, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 16, 16, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 16, 16, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 8, 8, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        38,950 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,202,758 (8.40 MB)

 Trainable params: 2,202,758 (8.40 MB)

 Non-trainable params: 0 (0.00 B)